EXTRACTED_OVERRIDES = {
    "    Monster": "专长",
    "**": "专长",
    "**Extreme Mood Swings": "专长",
    "25+5尺/2等级": "法术",
    "25尺+5尺/2等级": "法术",
    "400尺+40尺/等级": "法术",
    "ALLY": "专长",
    "AUTONOMY": "专长",
    "Aberration": "法术",
    "Abilities": "法术",
    "Abilities, Sp": "法术",
    "Abilities, Su": "法术",
    "Abjuration": "法术",
    "Absorbing Touch": "法术",
    "Accelerate Poison": "法术",
    "Acid Arrow": "法术",
    "Acid Fog": "法术",
    "Acid Pit": "法术",
    "Acid Splash": "法术",
    "Acidic Spray": "法术",
    "Acorn ": "法术",
    "Acrobatic Steps": "怪物/生物",
    "Acupuncture ": "专长",
    "Adaptation": "专长",
    "Adding ": "法术",
    "Adding Spells ": "法术",
    "Adjustment": "专长",
    "Advanced Race Guide": "种族",
    "Aegis": "专长",
    "Aeylinth酿酒厂": "专长",
    "Affirmations": "专长",
    "Age": "专长",
    "Aid": "法术",
    "Aid Another": "种族",
    "Aiming a ": "法术",
    "Air Walk": "法术",
    "Alarm": "法术",
    "Alchemical Allocation": "法术",
    "Alchemical Weapons": "装备/物品",
    "Aldori Swordlord": "装备/物品",
    "Align Weapon": "法术",
    "Aligned Crafting": "专长",
    "Alignment": "专长",
    "Alignment ": "专长",
    "Allfood": "法术",
    "Alter Self": "法术",
    "Alter Winds": "法术",
    "Ambush ": "专长",
    "Amplify ": "法术",
    "Analyze Dweomer": "法术",
    "Animal": "法术",
    "Animal ": "专长",
    "Animal Growth": "法术",
    "Animal Messenger": "法术",
    "Animal Shapes": "法术",
    "Animal Trance": "法术",
    "Animals": "专长",
    "Animate Dead": "法术",
    "Animate Objects": "法术",
    "Animate Plants": "法术",
    "Animate Rope": "法术",
    "Ant Haul": "法术",
    "Antilife Shell": "法术",
    "Antimagic Field": "法术",
    "Antipathy": "法术",
    "Antiplant Shell": "法术",
    "Antitoxin": "专长",
    "Apparent ": "专长",
    "Apparent Source of ": "专长",
    "Approach": "法术",
    "Aqueous ": "法术",
    "Arcane ": "法术",
    "Arcane Anthology": "法术",
    "Arcane Bond": "法术",
    "Arcane Eye": "法术",
    "Arcane Lock": "法术",
    "Arcane Mark": "法术",
    "Arcane School": "法术",
    "Arcane Sight": "法术",
    "Arcane Sight, Greater": "法术",
    "Arcane Strike": "专长",
    "Arctic ": "专长",
    "Area": "法术",
    "Area ": "法术",
    "Armor": "法术",
    "Armor Master": "装备/物品",
    "Arrow ": "法术",
    "Arrows": "专长",
    "Aspect of the ": "法术",
    "Aspects": "专长",
    "Astral Plane": "位面",
    "Astral Projection": "法术",
    "Atonement": "法术",
    "Attacks": "法术",
    "Audible ": "法术",
    "Augment Summoning": "法术",
    "Augury": "法术",
    "Aura Flare": "专长",
    "Aura Power": "法术",
    "Aura Strength": "法术",
    "Aura of Greater ": "法术",
    "Auspicious ": "专长",
    "Automatic ": "法术",
    "Avoid Int/Cha ": "法术",
    "Awaken": "法术",
    "Awareness": "专长",
    "BRACERS OF ARCHERY": "装备/物品",
    "BURGLAR BOOTS": "装备/物品",
    "Baleful Polymorph": "法术",
    "Ball ": "法术",
    "Bane": "法术",
    "Banish ": "法术",
    "Banishment": "法术",
    "Bard's ": "法术",
    "Bardic Performance": "职业能力",
    "Barkskin": "法术",
    "Barred ": "法术",
    "Battlefield Healer": "技能",
    "Battlemind Link": "怪物/生物",
    "Bear": "法术",
    "Bear's Endurance": "法术",
    "Bear's Endurance, Mass": "法术",
    "Beast Shape I": "法术",
    "Beast Shape II": "法术",
    "Beast Shape III": "法术",
    "Beast Shape IV": "法术",
    "Beguiling ": "法术",
    "Bellflower Tiller": "种族",
    "Bestow Curse": "法术",
    "Bestow Grace": "法术",
    "Binding": "法术",
    "Biography": "法术",
    "Birth": "专长",
    "Black Tentacles": "法术",
    "Blade Barrier": "法术",
    "Blasphemy": "法术",
    "Blast": "法术",
    "Blast ": "法术",
    "Blasting ": "专长",
    "Blaze of ": "法术",
    "Bleed": "法术",
    "Bleeding Critical": "动作/战技",
    "Bless": "法术",
    "Bless Water": "法术",
    "Bless Weapon": "法术",
    "Blessing of ": "法术",
    "Blessings": "专长",
    "Blight": "法术",
    "Blinded": "法术",
    "Blindness/Deafness": "法术",
    "Blink": "法术",
    "Blood ": "法术",
    "Bloodhound": "法术",
    "Bloodline Powers": "法术",
    "Bloody ": "法术",
    "Blur": "法术",
    "Bolt": "法术",
    "Bomber's ": "法术",
    "Bombs": "法术",
    "Bonded Mind，团队": "专长",
    "Bonds": "法术",
    "Bonus Feats": "专长",
    "Bonus Types": "法术",
    "Boon ": "专长",
    "Borrow ": "法术",
    "Boulder": "专长",
    "Bound ": "法术",
    "Bow Spirit": "法术",
    "Brand": "法术",
    "Brand, ": "法术",
    "Break": "法术",
    "Break Enchantment": "法术",
    "Breath": "法术",
    "Breath of Life": "法术",
    "Breed": "专长",
    "Brew Potion": "装备/物品",
    "Brilliant ": "法术",
    "Bringing Back the Dead": "法术",
    "Bristle": "法术",
    "Brute": "专长",
    "Bull's Strength": "法术",
    "Bull's Strength, Mass": "法术",
    "Burning ": "法术",
    "Burning Hands": "法术",
    "Burst ": "法术",
    "Burst, Emanation, or Spread": "法术",
    "CENTER OF POWER": "专长",
    "CHANNEL ": "专长",
    "Cacophonous ": "法术",
    "Cage": "法术",
    "Calcific ": "法术",
    "Call": "法术",
    "Call ": "法术",
    "Call Lightning": "法术",
    "Call Lightning Storm": "法术",
    "Call, Mass": "法术",
    "Calling": "法术",
    "Calling ": "法术",
    "Calm Animals": "法术",
    "Calm Emotions": "法术",
    "Camouflaged ": "专长",
    "Campfire ": "法术",
    "Careful ": "专长",
    "Cartographer": "专长",
    "Cast Out": "法术",
    "Caster": "专长",
    "Caster Level, CL": "法术",
    "Castigate": "法术",
    "Castigate, ": "法术",
    "Casting ": "法术",
    "Casting Defensively": "法术",
    "Casting Limit": "法术",
    "Casting Limit/Rest Interruptions": "法术",
    "Casting Spells": "法术",
    "Cat's Grace": "法术",
    "Cat's Grace, Mass": "法术",
    "Cause Fear": "法术",
    "Cave, Cavern, or ": "法术",
    "Cayden Cailean": "神祇",
    "Cell": "法术",
    "Chain Lightning": "法术",
    "Chaining": "法术",
    "Chains": "专长",
    "Chakra ": "专长",
    "Challenge ": "法术",
    "Chameleon ": "法术",
    "Changestaff": "法术",
    "Channel": "专长",
    "Channel Deific ": "专长",
    "Chaos Hammer": "法术",
    "Charge Object": "动作/战技",
    "Charm": "法术",
    "Charm Animal": "法术",
    "Charm Monster": "法术",
    "Charm Monster, Mass": "法术",
    "Charm Person": "法术",
    "Child ": "专长",
    "Chill ": "法术",
    "Chill Metal": "法术",
    "Chill Touch": "法术",
    "Choosing a Spell": "法术",
    "Circle of Death": "法术",
    "Clairaudience/Clairvoyance": "法术",
    "Clashing ": "法术",
    "Class": "法术",
    "Class Features": "职业能力",
    "Class Skills": "职业能力",
    "Claws": "法术",
    "Cleanse": "法术",
    "Clenched Fist": "法术",
    "Cliffs": "法术",
    "Climber": "专长",
    "Cloak of ": "法术",
    "Cloak of Chaos": "法术",
    "Clockwork Familiar": "怪物/生物",
    "Clone": "法术",
    "Close": "法术",
    "Cloudkill": "法术",
    "Color Spray": "法术",
    "Comatose": "法术",
    "Combat ": "法术",
    "Combat Expertise": "专长",
    "Combat Reflexes": "专长",
    "Combat Style": "怪物/生物",
    "Combat Trick": "怪物/生物",
    "Combining Magic Effects": "法术",
    "Command": "法术",
    "Command ": "专长",
    "Command Plants": "法术",
    "Command Undead": "法术",
    "Command, Greater": "法术",
    "Commune": "法术",
    "Commune with Nature": "法术",
    "Companion": "专长",
    "Companion ": "专长",
    "Components": "法术",
    "Comprehend Languages": "法术",
    "Compulsion": "法术",
    "Concentration": "法术",
    "Concordance": "法术",
    "Cone of Cold": "法术",
    "Cone, ": "法术",
    "Confused": "法术",
    "Confusion": "法术",
    "Confusion, Lesser": "法术",
    "Conjuration": "法术",
    "Consecrate": "法术",
    "Construction Points": "怪物/生物",
    "Consumption": "法术",
    "Contact Other Plane": "法术",
    "Contagion": "法术",
    "Containment": "法术",
    "Contingency": "法术",
    "Continual Flame": "法术",
    "Control Plants": "法术",
    "Control Undead": "法术",
    "Control Water": "法术",
    "Control Weather": "法术",
    "Control Winds": "法术",
    "Corsair of ": "专长",
    "Costs": "法术",
    "Counterspell": "法术",
    "Counterspelling Metamagic Spells": "法术",
    "Counterspells": "法术",
    "Courage": "法术",
    "Courage and Life": "法术",
    "Cover ": "专长",
    "Craft Construct": "专长",
    "Craft Wondrous Item": "专长",
    "Crafter": "专长",
    "Cranial ": "专长",
    "Create Demiplane": "位面",
    "Create Enhanced Firearm": "专长",
    "Create Food and Water": "法术",
    "Create Greater Undead": "法术",
    "Create Undead": "法术",
    "Create Water": "法术",
    "Creation": "法术",
    "Creatures": "法术",
    "Creeping Doom": "法术",
    "Critical Focus": "动作/战技",
    "Crushing Despair": "法术",
    "Crushing Hand": "法术",
    "Cunning": "专长",
    "Cure Critical Wounds": "法术",
    "Cure Critical Wounds, Mass": "法术",
    "Cure Light Wounds": "法术",
    "Cure Light Wounds, Mass": "法术",
    "Cure Moderate Wounds": "法术",
    "Cure Moderate Wounds, Mass": "法术",
    "Cure Serious Wounds": "法术",
    "Cure Serious Wounds, Mass": "法术",
    "Curious ": "专长",
    "Curse Water": "法术",
    "Cylinder, Line, or Sphere": "法术",
    "DETACHMENT": "专长",
    "Daily ": "法术",
    "Dancing ": "法术",
    "Dancing Lights": "法术",
    "Darkness": "法术",
    "Darkvision": "法术",
    "Day": "法术",
    "Day Job": "种族",
    "Daylight": "法术",
    "Daze": "法术",
    "Daze Monster": "法术",
    "Dazed": "法术",
    "Deadly ": "法术",
    "Deafened": "法术",
    "Deafening Song ": "法术",
    "Death Knell": "法术",
    "Death Ward": "法术",
    "Death and ": "法术",
    "Deathwatch": "法术",
    "Decrease": "法术",
    "Decrepit Disguise": "技能",
    "Deep ": "专长",
    "Deep Slumber": "法术",
    "Deeper Darkness": "法术",
    "Defile ": "法术",
    "Deflection": "法术",
    "Delay Poison": "法术",
    "Delayed ": "法术",
    "Delayed Blast Fireball": "法术",
    "Deliver Touch Spells": "法术",
    "Delver": "专长",
    "Demand": "法术",
    "Demon Fever": "怪物/生物",
    "Denounce": "法术",
    "Deny Death": "状态/条件",
    "Descriptive ": "法术",
    "Desecrate": "法术",
    "Desert ": "专长",
    "Destruction": "法术",
    "Detect ": "法术",
    "Detect Animals or Plants": "法术",
    "Detect Chaos": "法术",
    "Detect Evil": "法术",
    "Detect Good": "法术",
    "Detect Law": "法术",
    "Detect Magic": "法术",
    "Detect Poison": "法术",
    "Detect Scrying": "法术",
    "Detect Secret Doors": "法术",
    "Detect Snares and Pits": "法术",
    "Detect Thoughts": "法术",
    "Detect Undead": "法术",
    "Detonate": "法术",
    "Devolution": "法术",
    "Devotion against the ": "专长",
    "Dictum": "法术",
    "Different Bonus Types": "法术",
    "Dilemmas": "专长",
    "Dilettante": "专长",
    "Dimension Door": "法术",
    "Dimensional Anchor": "法术",
    "Dimensional Lock": "法术",
    "Diminish Plants": "法术",
    "Direction of Spell's ": "专长",
    "Dirty Tactics Toolbox": "法术",
    "Disable Device": "技能",
    "Disarming Strike": "动作/战技",
    "Disbelief": "法术",
    "Discern Lies": "法术",
    "Discern Location": "法术",
    "Discharge": "法术",
    "Disciple": "专长",
    "Discordant ": "法术",
    "Disguise": "专长",
    "Disguise Self": "法术",
    "Disintegrate": "法术",
    "Dislocate": "专长",
    "Dismissal": "法术",
    "Dismissible": "法术",
    "Dispel": "法术",
    "Dispel Chaos": "法术",
    "Dispel Evil": "法术",
    "Dispel Good": "法术",
    "Dispel Law": "法术",
    "Dispel Magic": "法术",
    "Dispel Magic as a ": "法术",
    "Dispel Magic, Greater": "法术",
    "Displacement": "法术",
    "Disrupt Undead": "法术",
    "Disrupting Weapon": "法术",
    "Diver": "专长",
    "Divination": "法术",
    "Divination School": "职业能力",
    "Divine ": "法术",
    "Divine Bond": "法术",
    "Divine Boon": "神祇",
    "Divine Favor": "法术",
    "Divine Focus, DF": "法术",
    "Divine Grace": "神祇",
    "Divine Inks": "法术",
    "Divine Power": "法术",
    "Divine Spells": "法术",
    "Don't Know": "法术",
    "Doom": "法术",
    "Doors": "法术",
    "Draconic ": "法术",
    "Dragon's ": "法术",
    "Dream": "法术",
    "Dreams": "法术",
    "Drop": "法术",
    "Drunken ": "专长",
    "Drunken God's ": "专长",
    "Duration": "法术",
    "Dust of ": "法术",
    "Dweller": "专长",
    "EXPERT ": "专长",
    "Eagle's Splendor": "法术",
    "Eagle's Splendor, Mass": "法术",
    "Eagle-Eyed": "专长",
    "Earth ": "专长",
    "Earthquake": "法术",
    "Ectoplasmic Spell": "法术",
    "Edge": "专长",
    "Effect": "法术",
    "Effects": "专长",
    "Eldritch Heritage": "专长",
    "Elemental Body I": "法术",
    "Elemental Body II": "法术",
    "Elemental Body III": "法术",
    "Elemental Body IV": "法术",
    "Elemental Focus": "怪物/生物",
    "Elemental Grip": "怪物/生物",
    "Elemental Overflow": "怪物/生物",
    "Elemental Swarm": "法术",
    "Elemental Touch": "怪物/生物",
    "Elemental Whisper": "怪物/生物",
    "Elixir": "法术",
    "Empower Spell": "法术",
    "Enchantment": "法术",
    "Endure Elements": "法术",
    "Energized Wild ": "专长",
    "Energy Drain": "法术",
    "Energy Resistance": "法术",
    "Enervation": "法术",
    "Enhanced Gnome ": "专长",
    "Enlarge Person": "法术",
    "Enlarge Person, Mass": "法术",
    "Enmity": "专长",
    "Enrichment": "法术",
    "Entangle": "法术",
    "Entangled": "法术",
    "Enthrall": "法术",
    "Entropic Shield": "法术",
    "Environment": "法术",
    "Erase": "法术",
    "Eruption": "法术",
    "Escape": "法术",
    "Escape Artist": "技能",
    "Essence": "专长",
    "Eternal ": "专长",
    "Ethereal Envelope": "法术",
    "Ethereal Jaunt": "法术",
    "Ethereal Plane": "位面",
    "Etherealness": "法术",
    "Evil": "法术",
    "Evocation": "法术",
    "Ex": "法术",
    "Exotic ": "专长",
    "Expeditious Retreat": "法术",
    "Expert ": "专长",
    "Explorer": "专长",
    "Explosive Runes": "法术",
    "Expressed in Feet": "法术",
    "Extend Spell": "法术",
    "Extended ": "专长",
    "Extended Animal ": "专长",
    "Extra Gnome ": "专长",
    "Extraordinary Abilities, ": "法术",
    "Eye": "法术",
    "Eyebite": "法术",
    "FEATS": "专长",
    "FIRE GIANT ": "专长",
    "FOCUSED ": "专长",
    "FORTUNATE ": "专长",
    "Fabricate": "法术",
    "Faerie Fire": "法术",
    "Failures and Successes": "法术",
    "Fair": "法术",
    "Falcon": "法术",
    "Fall": "法术",
    "False ": "专长",
    "False Life": "法术",
    "False Vision": "法术",
    "Fast Movement": "职业能力",
    "Favored Animal ": "专长",
    "Fear": "法术",
    "Feather Fall": "法术",
    "Feather Step": "专长",
    "Feats": "专长",
    "Feature": "专长",
    "Feeblemind": "法术",
    "Fervor": "法术",
    "Fey ": "专长",
    "Fey-Guarded": "专长",
    "Fiend Totem": "怪物/生物",
    "Fiendish ": "专长",
    "Figment": "法术",
    "Finale": "法术",
    "Find Traps": "法术",
    "Find the Path": "法术",
    "Finger of Death": "法术",
    "Fire Seeds": "法术",
    "Fire Shield": "法术",
    "Fire Storm": "法术",
    "Fire Trap": "法术",
    "Fireball": "法术",
    "Flame Arrow": "法术",
    "Flame Blade": "法术",
    "Flame Strike": "法术",
    "Flaming Sphere": "法术",
    "Flare": "法术",
    "Flavor": "专长",
    "Flee": "法术",
    "Flesh to Stone": "法术",
    "Floating Disk": "法术",
    "Fly": "法术",
    "Focus": "专长",
    "Focus, F": "法术",
    "Foebane ": "专长",
    "Fog": "法术",
    "Fog Cloud": "法术",
    "Forbiddance": "法术",
    "Force": "法术",
    "Forcecage": "法术",
    "Forceful Hand": "法术",
    "Foresight": "法术",
    "Forge Ring": "装备/物品",
    "Form of the Dragon I": "法术",
    "Form of the Dragon II": "法术",
    "Form of the Dragon III": "法术",
    "Fortune": "法术",
    "Fox's Cunning": "法术",
    "Fox's Cunning, Mass": "法术",
    "Freedom": "法术",
    "Freedom of Movement": "法术",
    "Freezing Sphere": "法术",
    "Friendly Switch": "专长",
    "Frightful ": "专长",
    "Frost Mammoth": "法术",
    "GAUNTLET OF RUST": "装备/物品",
    "Gained at a New Level": "法术",
    "Gaseous Form": "法术",
    "Gate": "法术",
    "Gaze": "法术",
    "Geas, Lesser": "法术",
    "Geas/Quest": "法术",
    "Genie-Touched ": "专长",
    "Gentle Repose": "法术",
    "Ghost Sound": "法术",
    "Ghost Touch": "怪物/生物",
    "Ghostbane Dirge": "怪物/生物",
    "Ghoul Touch": "法术",
    "Giant Form I": "法术",
    "Giant Form II": "法术",
    "Giant Vermin": "法术",
    "Gift": "法术",
    "Giving up a Saving Throw": "法术",
    "Glamer": "法术",
    "Glibness": "法术",
    "Glitterdust": "法术",
    "Globe of Invulnerability": "法术",
    "Globe of Invulnerability, Lesser": "法术",
    "Glory": "法术",
    "Glyph": "法术",
    "Glyph of Warding": "法术",
    "Glyph of Warding, Greater": "法术",
    "Going Cosmic": "专长",
    "Good": "专长",
    "Good Hope": "法术",
    "Goodberry": "法术",
    "Grappling or Pinned": "法术",
    "Grasping ": "专长",
    "Grasping Hand": "法术",
    "Gray Ooze": "怪物/生物",
    "Grease": "法术",
    "Greater": "法术",
    "Greater Sunder": "动作/战技",
    "Greater Tactician": "法术",
    "Greater Tenacious ": "专长",
    "Greater Vital Strike": "专长",
    "Greater Weapon Focus": "装备/物品",
    "Grenades": "法术",
    "Ground": "法术",
    "Growth": "法术",
    "Growth Hex": "专长",
    "Guards and Wards": "法术",
    "Guidance": "法术",
    "Gust of Wind": "法术",
    "HAND": "专长",
    "HAND’S ": "专长",
    "HELM OF BRILLIANCE": "装备/物品",
    "Half": "法术",
    "Hallow": "法术",
    "Hallucinatory Terrain": "法术",
    "Halt": "法术",
    "Halt Undead": "法术",
    "Handle Animal": "技能",
    "Hardy ": "专长",
    "Harm": "法术",
    "Haruspicy": "专长",
    "Harvester": "专长",
    "Haste": "法术",
    "Heal": "法术",
    "Heal Mount": "法术",
    "Heal, Mass": "法术",
    "Healer": "专长",
    "Healing": "法术",
    "Heat Metal": "法术",
    "Hedged ": "法术",
    "Hefty ": "专长",
    "Heighten Spell": "法术",
    "Hellkngiht ": "专长",
    "Hellknight ": "专长",
    "Helping Hand": "法术",
    "Heritage": "专长",
    "Heroes' Feast": "法术",
    "Heroism": "法术",
    "Heroism, Greater": "法术",
    "Hex": "专长",
    "Hex Glyph": "法术",
    "Hide ": "专长",
    "Hide from Animals": "法术",
    "Hide from Undead": "法术",
    "Hideous Laughter": "法术",
    "Hit Die": "规则概念",
    "Hold Animal": "法术",
    "Hold Monster": "法术",
    "Hold Monster, Mass": "法术",
    "Hold Person": "法术",
    "Hold Person, Mass": "法术",
    "Hold Portal": "法术",
    "Holly Berry ": "法术",
    "Holy Aura": "法术",
    "Holy Smite": "法术",
    "Holy Sword": "法术",
    "Holy Word": "法术",
    "Horn of the Criosphinx, 战斗": "专长",
    "Horrid Wilting": "法术",
    "How Counterspells Work": "法术",
    "Hunter": "专长",
    "Hypnotic Pattern": "法术",
    "Hypnotism": "法术",
    "Ice ": "专长",
    "Ice Storm": "法术",
    "Identify": "法术",
    "Illusion": "法术",
    "Illusory Script": "法术",
    "Illusory Wall": "法术",
    "Imbue with Spell Ability": "法术",
    "Imitate a Dissimilar ": "专长",
    "Implantation": "专长",
    "Implosion": "法术",
    "Imprisonment": "法术",
    "Improve Toxicological ": "专长",
    "Improved Bull Rush": "专长",
    "Improved Critical": "动作/战技",
    "Improved Disarm": "专长",
    "Improved Evasion": "专长",
    "Improved Feint": "专长",
    "Improved Grapple": "专长",
    "Improved Great Fortitude": "专长",
    "Improved Iron Will": "专长",
    "Improved Natural ": "专长",
    "Improved Quarry": "专长",
    "Improved Reposition": "动作/战技",
    "Improved Trip": "专长",
    "Improved Unarmed Strike": "专长",
    "Improved Uncanny Dodge": "专长",
    "Improved Vital Strike": "专长",
    "Improvisational ": "专长",
    "Incendiary Cloud": "法术",
    "Incredible Healer": "专长",
    "Independent Research": "法术",
    "Inflict Critical Wounds": "法术",
    "Inflict Critical Wounds, Mass": "法术",
    "Inflict Light Wounds": "法术",
    "Inflict Light Wounds, Mass": "法术",
    "Inflict Moderate Wounds": "法术",
    "Inflict Moderate Wounds, Mass": "法术",
    "Inflict Pain": "法术",
    "Inflict Serious Wounds": "法术",
    "Inflict Serious Wounds, Mass": "法术",
    "Initiate": "专长",
    "Injury": "法术",
    "Inner Sea Gods": "地域",
    "Inner Sea Magic": "地域",
    "Insanity": "法术",
    "Inscribe Magical Tattoo": "专长",
    "Insect Plague": "法术",
    "Insight": "专长",
    "Inspiration": "法术",
    "Inspirational Commander": "专长",
    "Inspire Competence": "职业能力",
    "Instant Summons": "法术",
    "Instantaneous": "法术",
    "Instantaneous Effects": "法术",
    "Interplanetary Teleport": "位面",
    "Interposing Hand": "法术",
    "Invisibility": "法术",
    "Invisibility Purge": "法术",
    "Invisibility Sphere": "法术",
    "Invisibility, Greater": "法术",
    "Invisibility, Mass": "法术",
    "Iron Body": "法术",
    "Ironwood": "法术",
    "Irresistible Dance": "法术",
    "Items ": "法术",
    "Jump": "法术",
    "Jungle ": "专长",
    "KNOWLEDGE": "专长",
    "Keen Edge": "法术",
    "Ki Arrow": "装备/物品",
    "Killed": "法术",
    "Kinetic Healer": "技能",
    "Knock": "法术",
    "Know Direction": "法术",
    "Land": "专长",
    "Lantern": "法术",
    "Lawful": "专长",
    "Leaper": "专长",
    "Legend Lore": "法术",
    "Level": "法术",
    "Levitate": "法术",
    "Lie": "法术",
    "Life ": "专长",
    "Light": "法术",
    "Light Blindness": "状态/条件",
    "Lightning": "法术",
    "Lightning Bolt": "法术",
    "Lightning Reflexes": "专长",
    "Lightning Stance": "法术",
    "Limited Wish": "法术",
    "Line of Effect": "法术",
    "Lingering ": "专长",
    "Lingering Aura": "法术",
    "Liquid Courage": "职业能力",
    "Live off the ": "专长",
    "Liveoak": "法术",
    "Liver": "专长",
    "Locate Creature": "法术",
    "Locate Object": "法术",
    "Locks": "法术",
    "Long": "法术",
    "Longstrider": "法术",
    "Lost ": "法术",
    "Lower ": "法术",
    "Lullaby": "法术",
    "MANAGER": "专长",
    "MASK OF GIANTS": "怪物/生物",
    "MONKEY BELT": "装备/物品",
    "Magaambyan Arcanist": "法术",
    "Mage Armor": "法术",
    "Mage Hand": "法术",
    "Mage's Disjunction": "法术",
    "Mage's Faithful Hound": "法术",
    "Mage's Lucubration": "法术",
    "Mage's Magnificent Mansion": "法术",
    "Mage's Private Sanctum": "法术",
    "Mage's Sword": "法术",
    "Magic": "法术",
    "Magic Aura": "法术",
    "Magic Circle against Chaos": "法术",
    "Magic Circle against Evil": "法术",
    "Magic Circle against Good": "法术",
    "Magic Circle against Law": "法术",
    "Magic Fang": "法术",
    "Magic Fang, Greater": "法术",
    "Magic Item Creation": "装备/物品",
    "Magic Jar": "法术",
    "Magic Missile": "法术",
    "Magic Mouth": "法术",
    "Magic Shop": "法术",
    "Magic Siege Engine": "法术",
    "Magic Stone": "法术",
    "Magic Vestment": "法术",
    "Magic Weapon": "法术",
    "Magic Weapon, Greater": "法术",
    "Magic and Spell": "法术",
    "Magical Writings": "法术",
    "Major Creation": "法术",
    "Major Hex": "法术",
    "Major Image": "法术",
    "Major Magic": "法术",
    "Make Whole": "法术",
    "Mandala": "专长",
    "Maneuver": "法术",
    "Mark of Justice": "法术",
    "Marsh": "法术",
    "Martial Arts Handbook": "法术",
    "Mass": "法术",
    "Master": "专长",
    "Master ": "专长",
    "Material": "法术",
    "Material Plane": "位面",
    "Materials and ": "法术",
    "Maze": "法术",
    "Medium": "法术",
    "Meld into Stone": "法术",
    "Mending": "法术",
    "Mental ": "法术",
    "Message": "法术",
    "Metamorphosis": "法术",
    "Meteor Swarm": "法术",
    "Mind": "专长",
    "Mind Blank": "法术",
    "Mind Fog": "法术",
    "Mind Swap": "法术",
    "Mindspin Mountains": "地域",
    "Minimus ": "法术",
    "Minor Creation": "法术",
    "Minor Image": "法术",
    "Minor Magic": "法术",
    "Miracle": "法术",
    "Mirage Arcana": "法术",
    "Mirror Hideaway": "技能",
    "Mirror Image": "法术",
    "Mischievous ": "专长",
    "Misdirection": "法术",
    "Mislead": "法术",
    "Mnemonic Enhancer": "法术",
    "Modify Memory": "法术",
    "Moment of Prescience": "法术",
    "Moontouched": "专长",
    "Moral Challenges and ": "专长",
    "Morals": "专长",
    "Mount": "法术",
    "Mountaineer": "专长",
    "Mounted Combat": "怪物/生物",
    "Move Earth": "法术",
    "Muddled ": "专长",
    "Multiple Mental Control Effects": "法术",
    "Mutated ": "专长",
    "Mwangi Expanse": "地域",
    "Mystery": "专长",
    "Mystery Cultist": "组织/势力",
    "NATURAL ": "专长",
    "Name": "法术",
    "Natural Abilities": "法术",
    "Natural Poison ": "专长",
    "Nature Bond": "法术",
    "Nature's ": "专长",
    "Necromancy": "法术",
    "Negates": "法术",
    "Negative Levels": "法术",
    "Neutralize Poison": "法术",
    "New Divine ": "法术",
    "New Spell into a Spellbook": "法术",
    "Night Sky ": "专长",
    "Nightmare": "法术",
    "Nightmare ": "专长",
    "Nimble Moves": "动作/战技",
    "Nondetection": "法术",
    "None": "法术",
    "Normal": "法术",
    "OVERSEER": "专长",
    "Obedience": "专长",
    "Objects": "法术",
    "Obscure Object": "法术",
    "Obscuring Mist": "法术",
    "Obsession": "专长",
    "Occult Adventures": "组织/势力",
    "Occult Messenger": "组织/势力",
    "Occult Skill Unlock": "组织/势力",
    "Occult Skill Unlocks": "组织/势力",
    "One Effect Makes Another Irrelevant": "法术",
    "One Eye ": "专长",
    "One with the ": "专长",
    "Oozing ": "专长",
    "Open": "专长",
    "Open ": "法术",
    "Open/Close": "法术",
    "Orb": "法术",
    "Order's Wrath": "法术",
    "Other": "法术",
    "Out of the Sun, ": "专长",
    "Overgrowth": "法术",
    "Overland Flight": "法术",
    "Overwhelming ": "专长",
    "Owl's Wisdom": "法术",
    "Owl's Wisdom, Mass": "法术",
    "POSSESSED ": "专长",
    "PRECOCIOUS ": "专长",
    "Panicked": "法术",
    "Paralyzed": "法术",
    "Partial": "法术",
    "Pass without Trace": "法术",
    "Passwall": "法术",
    "Pathfinder Society": "组织/势力",
    "Pathologist": "专长",
    "Pattern": "法术",
    "Performance": "专长",
    "Permanency": "法术",
    "Permanent": "法术",
    "Permanent Image": "法术",
    "Persistent Image": "法术",
    "Personal": "法术",
    "Phantasm": "法术",
    "Phantasmal Killer": "法术",
    "Phantom": "专长",
    "Phantom Steed": "法术",
    "Phantom Trap": "法术",
    "Phase Door": "法术",
    "Pinned Beneath ": "法术",
    "Planar ": "法术",
    "Planar Ally": "法术",
    "Planar Ally, Greater": "法术",
    "Planar Ally, Lesser": "法术",
    "Planar Binding": "法术",
    "Planar Binding, Greater": "法术",
    "Planar Binding, Lesser": "法术",
    "Plane Shift": "法术",
    "Plant Growth": "法术",
    "Plant Shape I": "法术",
    "Plant Shape II": "法术",
    "Plant Shape III": "法术",
    "Plants": "专长",
    "Poison": "法术",
    "Poison ": "专长",
    "Poison Resistance": "装备/物品",
    "Poison Use": "装备/物品",
    "Poisoner": "专长",
    "Polar Ray": "法术",
    "Polymorph": "法术",
    "Polymorph Any Object": "法术",
    "Polymorph, Greater": "法术",
    "Poor": "法术",
    "Potency": "专长",
    "Power Word Blind": "法术",
    "Power Word Kill": "法术",
    "Power Word Stun": "法术",
    "Prayer": "法术",
    "Precise Shot": "专长",
    "Preparation ": "法术",
    "Preparation Time": "法术",
    "Prepare": "法术",
    "Prepared ": "法术",
    "Prepared Spell Retention": "法术",
    "Preparing ": "法术",
    "Prestidigitation": "法术",
    "Preventing Revivification": "法术",
    "Prismatic Sphere": "法术",
    "Prismatic Spray": "法术",
    "Prismatic Wall": "法术",
    "Prison": "法术",
    "Produce Flame": "法术",
    "Programmed Image": "法术",
    "Project Image": "法术",
    "Protection from Arrows": "法术",
    "Protection from Chaos": "法术",
    "Protection from Energy": "法术",
    "Protection from Evil": "法术",
    "Protection from Good": "法术",
    "Protection from Law": "法术",
    "Protection from Spells": "法术",
    "Prune ": "法术",
    "Prying Eyes": "法术",
    "Prying Eyes, Greater": "法术",
    "Psychic ": "法术",
    "Psychic Discipline": "位面",
    "Purify Food and Drink": "法术",
    "Purifying ": "专长",
    "Pyrotechnics": "法术",
    "Quench": "法术",
    "Quicken Spell": "法术",
    "RIDDEN": "专长",
    "RULER": "专长",
    "Rage": "法术",
    "Rage Powers": "职业能力",
    "Raging Swimmer": "技能",
    "Rainbow Pattern": "法术",
    "Raise ": "法术",
    "Raise Animal Companion": "怪物/生物",
    "Raise Dead": "法术",
    "Random Answer": "法术",
    "Range": "法术",
    "Range ": "法术",
    "Ray": "法术",
    "Ray of Enfeeblement": "法术",
    "Ray of Exhaustion": "法术",
    "Ray of Frost": "法术",
    "Read Magic": "法术",
    "Read the ": "专长",
    "Reader": "专长",
    "Readying of Spells": "法术",
    "Recent ": "法术",
    "Reduce Animal": "法术",
    "Reduce Person": "法术",
    "Reduce Person, Mass": "法术",
    "Refuge": "法术",
    "Regenerate": "法术",
    "Regular": "专长",
    "Reincarnate": "法术",
    "Reinforce Crafting": "专长",
    "Remove ": "法术",
    "Remove Curse": "法术",
    "Remove Disease": "法术",
    "Remove Fear": "法术",
    "Remove Paralysis": "法术",
    "Repair Undead": "怪物/生物",
    "Repel Metal or Stone": "法术",
    "Repel Vermin": "法术",
    "Repel Wood": "法术",
    "Replacing ": "法术",
    "Repulsion": "法术",
    "Reservoir": "法术",
    "Resilient Sphere": "法术",
    "Resist Energy": "法术",
    "Resistance": "法术",
    "Resistance, SR": "法术",
    "Rest": "法术",
    "Restoration": "法术",
    "Restoration, Greater": "法术",
    "Restoration, Lesser": "法术",
    "Results": "法术",
    "Resurrection": "法术",
    "Retain": "法术",
    "Retributive ": "专长",
    "Returning Weapon": "装备/物品",
    "Reverse Gravity": "法术",
    "Revivification against One's Will": "法术",
    "Rider": "专长",
    "Righteous Might": "法术",
    "Ritual Hex": "专长",
    "River, Lake, or ": "法术",
    "Rocks": "法术",
    "Room": "专长",
    "Rope Trick": "法术",
    "Royal Enforcer": "怪物/生物",
    "Rubble": "法术",
    "Rush": "专长",
    "Rusting Grasp": "法术",
    "SERPENT BELT": "装备/物品",
    "SIGHT": "专长",
    "SPIRIT": "专长",
    "SPIRIT ": "专长",
    "SPIRITUAL ": "专长",
    "SUPERINTENDENT": "专长",
    "Sacrificial ": "专长",
    "Salvager": "专长",
    "Same Effect More than Once ": "法术",
    "Same Effect with Differing ": "法术",
    "Sanctuary": "法术",
    "Saving ": "法术",
    "Saving Throw": "状态/条件",
    "Saving Throw Difficulty ": "法术",
    "Saving Throws and Illusions, ": "法术",
    "Scare": "法术",
    "School": "专长",
    "School and Subschool": "法术",
    "Scintillating Pattern": "法术",
    "Scorching Ray": "法术",
    "Screen": "法术",
    "Scribe Scroll": "专长",
    "Scrutinize ": "专长",
    "Scrying": "法术",
    "Scrying, Greater": "法术",
    "Sculpt Sound": "法术",
    "Searing Light": "法术",
    "Secret ": "专长",
    "Secret Chest": "法术",
    "Secret Page": "法术",
    "Secure Shelter": "法术",
    "See Invisibility": "法术",
    "Seeming": "法术",
    "Selection and Preparation": "法术",
    "Selling a ": "法术",
    "Sending": "法术",
    "Sense": "专长",
    "Sense Motive": "技能",
    "Senses": "专长",
    "Sepia Snake Sigil": "法术",
    "Sequester": "法术",
    "Shades": "法术",
    "Shadow": "法术",
    "Shadow Conjuration": "法术",
    "Shadow Conjuration, Greater": "法术",
    "Shadow Evocation": "法术",
    "Shadow Evocation, Greater": "法术",
    "Shadow Plane": "位面",
    "Shadow Walk": "法术",
    "Shambler": "法术",
    "Shape": "专长",
    "Shapeable": "法术",
    "Shapechange": "法术",
    "Share ": "专长",
    "Share Spells": "法术",
    "Shatter": "法术",
    "Shield": "法术",
    "Shield Focus": "装备/物品",
    "Shield Other": "法术",
    "Shield Wall": "装备/物品",
    "Shield of Faith": "法术",
    "Shield of Law": "法术",
    "Shifter’s ": "专长",
    "Shifts and ": "专长",
    "Shillelagh": "法术",
    "Shocking Grasp": "法术",
    "Shout": "法术",
    "Shout, Greater": "法术",
    "Shrink Item": "法术",
    "Shrouded in ": "专长",
    "Sickened": "法术",
    "Sight": "专长",
    "Signifer Armor ": "专长",
    "Silence": "法术",
    "Silent Image": "法术",
    "Silent Spell": "法术",
    "Simulacrum": "法术",
    "Sing-Along": "专长",
    "Skeletons": "法术",
    "Skill": "法术",
    "Skill Focus": "专长",
    "Slay Living": "法术",
    "Sleep": "法术",
    "Sleet Storm": "法术",
    "Slow": "法术",
    "Slow Fall": "法术",
    "Slumber": "法术",
    "Smite": "专长",
    "Smite Evil": "法术",
    "Snare": "法术",
    "Snatch ": "专长",
    "Soften Earth and Stone": "法术",
    "Solid Fog": "法术",
    "Somatic, S": "法术",
    "Song of Discord": "法术",
    "Sonic Thrust": "法术",
    "Sorcerers ": "法术",
    "Soul Bind": "法术",
    "Soul-Powered ": "专长",
    "Soulblade": "专长",
    "Souls": "专长",
    "Soulwrecking Strike": "专长",
    "Sound Burst": "法术",
    "Space in the ": "法术",
    "Speak with Animals": "法术",
    "Speak with Dead": "法术",
    "Speak with Plants": "法术",
    "Special ": "法术",
    "Special Spell Effects": "法术",
    "Specialist": "专长",
    "Specific Exceptions": "法术",
    "Spectral Hand": "法术",
    "Spectrum ": "专长",
    "Spell": "法术",
    "Spell ": "法术",
    "Spell Completion": "法术",
    "Spell Descriptions": "法术",
    "Spell Failure": "法术",
    "Spell Focus": "法术",
    "Spell Immunity": "法术",
    "Spell Immunity, Greater": "法术",
    "Spell Mastery": "法术",
    "Spell Resistance": "法术",
    "Spell Retention": "法术",
    "Spell Slots": "法术",
    "Spell Trigger": "法术",
    "Spell Turning": "法术",
    "Spell-Like ": "法术",
    "Spellbook": "法术",
    "Spells": "法术",
    "Spells ": "法术",
    "Spells Copied from Another's Spellbook or a Scroll": "法术",
    "Spells and Borrowed Spellbooks": "法术",
    "Spells and Holding the Charge": "法术",
    "Spells to a Wizard's Spellbook": "法术",
    "Spells with Opposite Effects": "法术",
    "Spellstaff": "法术",
    "Spider Climb": "法术",
    "Spike Growth": "法术",
    "Spike Stones": "法术",
    "Spiritual Bond": "职业能力",
    "Spiritual Weapon": "法术",
    "Spontaneous Casting of Cure and Inflict Spells": "法术",
    "Spontaneous Casting of Summon Nature's Ally Spells": "法术",
    "Spontaneous Healing": "技能",
    "Spread": "法术",
    "Spurt，战斗": "专长",
    "Stabilize": "法术",
    "Stacking Effects": "法术",
    "Stag": "法术",
    "Staggered": "法术",
    "Staggering Blast": "装备/物品",
    "Standard ": "专长",
    "Statue": "法术",
    "Status": "法术",
    "Still Spell": "法术",
    "Stinking Cloud": "法术",
    "Stone Shape": "法术",
    "Stone Tell": "法术",
    "Stone to Flesh": "法术",
    "Stoneskin": "法术",
    "Storm ": "专长",
    "Storm of Vengeance": "法术",
    "Storm-Lashed": "专长",
    "Stride": "法术",
    "Structure": "法术",
    "Stunned": "法术",
    "Stunt ": "法术",
    "Su": "专长",
    "Subjects, Effects, and Areas": "法术",
    "Subtle ": "专长",
    "Succeeding on a Saving ": "法术",
    "Suggestion": "法术",
    "Suggestion, Mass": "法术",
    "Summon Evil ": "专长",
    "Summon Instrument": "法术",
    "Summon Monster": "法术",
    "Summon Monster I": "法术",
    "Summon Monster II": "法术",
    "Summon Monster III": "法术",
    "Summon Monster IV": "法术",
    "Summon Monster IX": "法术",
    "Summon Monster V": "法术",
    "Summon Monster VI": "法术",
    "Summon Monster VII": "法术",
    "Summon Monster VIII": "法术",
    "Summon Nature's Ally I": "法术",
    "Summon Nature's Ally II": "法术",
    "Summon Nature's Ally III": "法术",
    "Summon Nature's Ally IV": "法术",
    "Summon Nature's Ally IX": "法术",
    "Summon Nature's Ally V": "法术",
    "Summon Nature's Ally VI": "法术",
    "Summon Nature's Ally VII": "法术",
    "Summon Nature's Ally VIII": "法术",
    "Summon Swarm": "法术",
    "Summoning": "法术",
    "Sunbeam": "法术",
    "Sunburst": "法术",
    "Supernatural ": "法术",
    "Suppress Audible or Visible ": "专长",
    "Survivalist": "专长",
    "Surviving after a Saving Throw": "法术",
    "Survivor": "专长",
    "Sustained ": "法术",
    "Swamper": "专长",
    "Symbol of Death": "法术",
    "Symbol of Fear": "法术",
    "Symbol of Insanity": "法术",
    "Symbol of Pain": "法术",
    "Symbol of Persuasion": "法术",
    "Symbol of Sleep": "法术",
    "Symbol of Stunning": "法术",
    "Symbol of Weakness": "法术",
    "Sympathetic Vibration": "法术",
    "Sympathy": "法术",
    "TRAINER": "专长",
    "TRAINING": "专长",
    "Tail": "专长",
    "Taldor": "专长",
    "Target or ": "法术",
    "Targeted ": "法术",
    "Targets": "法术",
    "Tavern ": "专长",
    "Telekinesis": "法术",
    "Telekinetic Sphere": "法术",
    "Telepathic Bond": "法术",
    "Teleport": "法术",
    "Teleport ": "专长",
    "Teleport Object": "法术",
    "Teleport, Greater": "法术",
    "Teleportation": "法术",
    "Teleportation Circle": "法术",
    "Temporal Stasis": "法术",
    "Tenacious ": "专长",
    "Text": "法术",
    "The Inner Sea World Guide": "地域",
    "The Spell's Result": "法术",
    "The Value of ": "专长",
    "Throw": "法术",
    "Throw Anything": "专长",
    "Thrown Weapon": "装备/物品",
    "Thrust": "法术",
    "Thuvian Grenadier, 团队": "专长",
    "Time": "法术",
    "Time Stop": "法术",
    "Time of ": "法术",
    "Timed Durations": "法术",
    "Timing": "专长",
    "Timing and Focus": "专长",
    "Tiny Hut": "法术",
    "Tolerance": "专长",
    "Tongues": "法术",
    "Torrid ": "专长",
    "Totemic ": "专长",
    "Touch": "法术",
    "Touch ": "法术",
    "Touch of Evil": "专长",
    "Touch of Fatigue": "法术",
    "Touch of Idiocy": "法术",
    "Toxicological ": "专长",
    "Tracks": "专长",
    "Trail": "专长",
    "Training": "专长",
    "Transfer": "法术",
    "Transformation": "法术",
    "Transmutation": "法术",
    "Transmute Metal to Wood": "法术",
    "Transmute Mud to Rock": "法术",
    "Transmute Rock to Mud": "法术",
    "Transport via Plants": "法术",
    "Trap": "专长",
    "Trap Sense": "职业能力",
    "Trap the Soul": "法术",
    "Travel": "法术",
    "Tree ": "专长",
    "Tree Shape": "法术",
    "Tree Stride": "法术",
    "Trepanation": "专长",
    "Trophy Hunter": "种族",
    "True ": "专长",
    "True Answer": "法术",
    "True Resurrection": "法术",
    "True Seeing": "法术",
    "True Strike": "法术",
    "Tunnel": "法术",
    "Twilight": "法术",
    "Twilight Knife": "装备/物品",
    "Ultimate Magic": "法术",
    "Ultimate Wilderness": "地域",
    "Unadulterated Loathing": "怪物/生物",
    "Unbreakable Construct": "怪物/生物",
    "Uncanny Dodge": "专长",
    "Undeath to Death": "法术",
    "Undermine, 团队": "专长",
    "Undetectable Alignment": "法术",
    "Unhallow": "法术",
    "Unholy Aura": "法术",
    "Unholy Blight": "法术",
    "Unlimited": "法术",
    "Unnatural": "专长",
    "Unseen Servant": "法术",
    "Vampiric touch": "法术",
    "Vat": "专长",
    "Veil": "法术",
    "Ventriloquism": "法术",
    "Verbal, V": "法术",
    "Versatile Weapon": "装备/物品",
    "Vessel": "法术",
    "Vigorous Motion": "法术",
    "Vile ": "专长",
    "Violent ": "法术",
    "Violent Motion": "法术",
    "Violent Weather": "法术",
    "Virtue": "法术",
    "Vision": "法术",
    "Vital Strike": "专长",
    "Vocal Alteration": "怪物/生物",
    "Void Healer": "技能",
    "Voluntarily ": "法术",
    "WORKER": "专长",
    "Wail of the Banshee": "法术",
    "Wall": "法术",
    "Wall of Fire": "法术",
    "Wall of Force": "法术",
    "Wall of Ice": "法术",
    "Wall of Iron": "法术",
    "Wall of Stone": "法术",
    "Wall of Thorns": "法术",
    "War Lance": "装备/物品",
    "Warding Weapon": "装备/物品",
    "Warm ": "法术",
    "Warp Wood": "法术",
    "Water": "法术",
    "Water Breathing": "法术",
    "Water Walk": "法术",
    "Waterway ": "专长",
    "Waves of Exhaustion": "法术",
    "Waves of Fatigue": "法术",
    "Weak": "法术",
    "Weakened": "法术",
    "Weapon Familiarity": "装备/物品",
    "Weapon Finesse": "专长",
    "Weapon Focus": "专长",
    "Weapon Master": "装备/物品",
    "Weapon Training": "职业能力",
    "Web": "法术",
    "Webs": "法术",
    "Weird": "法术",
    "Whirlwind": "法术",
    "Whirlwind Attack": "专长",
    "Whispering Wind": "法术",
    "Wild ": "专长",
    "Wild Growth ": "专长",
    "Wild Vigor": "专长",
    "Wilding": "专长",
    "Wilding ": "专长",
    "Wind Direction": "法术",
    "Wind Strength": "法术",
    "Wind Walk": "法术",
    "Wind Wall": "法术",
    "Windowless ": "法术",
    "Wings": "专长",
    "Wings of the Androsphinx, 战斗": "专长",
    "Winter Witch": "法术",
    "Wish": "法术",
    "Wizard ": "法术",
    "Wizard Spells": "法术",
    "Wolf": "法术",
    "Wolf ": "专长",
    "Wood ": "专长",
    "Wood Shape": "法术",
    "Word of Chaos": "法术",
    "Word of Recall": "法术",
    "Worker": "专长",
    "Writing a ": "法术",
    "YOUTH": "专长",
    "Zombies": "法术",
    "Zone of Silence": "法术",
    "Zone of Truth": "法术",
    "adhesive": "专长",
    "and Bards": "法术",
    "and Copying Spellbooks": "法术",
    "dominate animal": "法术",
    "dominate monster": "法术",
    "dominate person": "法术",
    "ghost ": "专长",
    "harmless": "法术",
    "http://45.79.87.129/bbs/index.php?topic=70596.0": "法术",
    "http://45.79.87.129/bbs/index.php?topic=83686.msg834008#msg834008": "法术",
    "http://45.79.87.129/bbs/index.php?topic=92772.msg860934#msg860934": "法术",
    "http://www.aonprd.com/images/PathfinderSocietySymbol.gif": "专长",
    "https://aonprd.com/images/PathfinderSocietySymbolN.gif": "专长",
    "https://www.aonprd.com/images/PathfinderSocietySymbol.gif": "专长",
    "https://www.aonprd.com/images/PathfinderSocietySymbolN.gif": "专长",
    "in Different Strengths": "法术",
    "leadership": "专长",
    "object": "法术",
    "of Steel-Shattering Spirit": "专长",
    "of Two Fates": "专长",
    "the Salamander": "法术",
    "to a Sorcerer's or Bard's Repertoire": "法术",
    "touch": "专长",
    "又译附魔系, ": "法术",
    "可怖女仆": "专长",
    "团队": "专长",
    "团队专长": "专长",
    "土/水": "专长",
    "土/火": "专长",
    "恶叉": "专长",
    "战斗": "专长",
    "战斗，团队": "专长",
    "战斗，派头": "专长",
    "战斗，流派": "专长",
    "戴斯娜": "法术",
    "排水渠": "专长",
    "故事": "专长",
    "气/土": "专长",
    "气/水": "专长",
    "气/火": "专长",
    "海峡俱乐部": "专长",
    "火/水": "专长",
    "简称奥术, Arcane Spells": "法术",
    "简称神术, Divine Spells": "法术",
    "耳语石头": "专长",
    "莎琳": "法术",
    "造物": "专长",
}
