"""Phase 3 人工补充覆盖表

对自动信号/来源提取无法覆盖的剩余 其他 术语进行人工分类。
按 PF 1e 常识与来源书上下文判断，优先处理高频项。
"""

MANUAL_OVERRIDES = {
    # ===== 法术 =====
    "Touch Treatment": "职业能力",
    "Mindscape Door": "法术",
    "Gather Power": "职业能力",
    "Air Step": "法术",
    "Defensive Roll": "职业能力",
    "Speak With Haunt": "法术",
    "Heightened Awareness": "法术",
    "Long Arm": "法术",
    "Marionette Possession": "法术",
    "Shadow Step": "法术",
    "Aura Sight": "法术",
    "Monkey Fish": "法术",
    "Stricken Heart": "法术",
    "Pernicious Poison": "法术",
    "Acute Senses": "法术",
    "Ablative Barrier": "法术",
    "Create Treasure Map": "法术",
    "Preserve Organs": "职业能力",
    "Reckless Infatuation": "法术",
    "Masterwork Transformation": "法术",
    "Euphoric Cloud": "法术",
    "Focused Scrutiny": "法术",
    "Ghostly Disguise": "法术",
    "Fickle Winds": "法术",
    "Web Shelter": "法术",
    "Thorn Body": "法术",
    "Anchored Step": "法术",
    "Extreme Flexibility": "法术",
    "Invisibility Alarm": "法术",
    "Mindlocked Messenger": "法术",
    "Phantom Blood": "法术",
    "Pierce Disguise": "法术",
    "Unbearable Brightness": "法术",
    "Polypurpose Panacea": "法术",
    "Oppressive Boredom": "法术",
    "Steal Voice": "法术",
    "Wartrain Mount": "法术",
    "Terrible Remorse": "法术",
    "Envious Urge": "法术",
    "Anticipate Peril": "法术",
    "Absorb Toxicity": "法术",
    "Perceive Cues": "法术",
    "Mad Monkeys": "法术",
    "Resonating Word": "法术",
    "Purge Spirit": "法术",
    "Time Shudder": "法术",
    "Cushioning Bands": "法术",
    "Seek Thoughts": "法术",
    "Hydraulic Torrent": "法术",
    "Excruciating Deformation": "法术",
    "Strangling Hair": "法术",
    "Instigate Psychic Duel": "法术",
    "Frightening Tune": "法术",
    "Phantasmal Web": "法术",
    "Vitriolic Mist": "法术",
    "Blood Biography": "法术",
    "Control Summoned Creature": "法术",
    "Distracting Cacophony": "法术",
    "Share Memory": "法术",
    "Eruptive Pustules": "法术",
    "Discordant Blast": "法术",
    "Sow Thought": "法术",
    "Dream Council": "法术",
    "Ectoplasmic Snare": "法术",
    "Emotive Block": "法术",
    "Entrap Spirit": "法术",
    "Ghost Whip": "法术",
    "Grave Words": "法术",
    "Mind Probe": "法术",
    "Telekinetic Projectile": "法术",
    "Mirror Polish": "法术",
    "Sunder Breaker": "法术",
    "Unprepared Combatant": "法术",
    "Howling Agony": "法术",
    "Foster Hatred": "法术",
    "Dancing Darkness": "法术",
    "Conjure Black Pudding": "法术",
    "Eagle Aerie": "法术",
    "Unshakable Chill": "法术",
    "Condensed Ether": "法术",
    "Evolution Surge": "法术",
    "Spiritual Ally": "法术",
    "Dream Feast": "法术",
    "Banish Seeming": "法术",
    "Lighten Object": "法术",
    "Elude Time": "法术",
    "Enter Image": "法术",
    "Adhesive Blood": "法术",
    "Adhesive Spittle": "法术",
    "Nauseating Trail": "法术",
    "Silent Table": "法术",
    "Sonic Scream": "法术",
    "Haunting Choir": "法术",
    "Primal Scream": "法术",
    "Joyful Rapture": "法术",
    "Feast On Fear": "法术",
    "Malicious Spite": "法术",
    "Smug Narcissism": "法术",
    "Flexible Fury": "法术",
    "Force Punch": "法术",
    "Fungal Infestation": "法术",
    "Ghost Brand": "法术",
    "Glue Seal": "法术",
    "Hidden Speech": "法术",
    "Honeyed Tongue": "法术",
    "Hostile Levitation": "法术",
    "Hungry Pit": "法术",
    "Ill Omen": "法术",
    "Instant Enemy": "法术",
    "Languid Bomb Admixture": "法术",
    "Leashed Shackles": "法术",
    "Magnifying Chime": "法术",
    "Majestic Image": "法术",
    "Mirror Polish": "法术",
    "Miserable Pity": "法术",
    "Molten Orb": "法术",
    "Nauseating Dart": "法术",
    "Negate Aroma": "法术",
    "Pox Pustules": "法术",
    "Primal Regression": "法术",
    "Psychic Duels": "法术",
    "Reloading Hands": "法术",
    "Resilient Reservoir": "法术",
    "Resinous Skin": "法术",
    "River Whip": "法术",
    "Shadow Body": "法术",
    "Shifted Steps": "法术",
    "Slowing Mud": "法术",
    "Spiked Pit": "法术",
    "Strong Jaw": "法术",
    "Summon Minor Monster": "法术",
    "Summoner Conduit": "法术",
    "Surmount Affliction": "法术",
    "Targeted Bomb Admixture": "法术",
    "Telekinetic Maneuver": "法术",
    "Temporary Resurrection": "法术",
    "Thorn Javelin": "法术",
    "Thought Echo": "法术",
    "Twilight Haze": "法术",
    "Vomit Twin": "法术",
    "Wilderness Soldiers": "法术",
    "Youthful Appearance": "法术",
    "Delayed Pain": "法术",
    "Deja Vu": "法术",
    "Diagnose Disease": "法术",
    "Defensive Shock": "法术",
    "Draconic Reservoir": "法术",
    "Elemental Speech": "法术",
    "Fire Breath": "法术",
    "Flare Burst": "法术",
    "Brow Gasher": "法术",
    "Certain Grip": "法术",
    "Creeping Ice": "法术",
    "Crimson Confession": "法术",
    "Blood Sentinel": "法术",
    "Blood Transcription": "法术",
    "Age Resistance": "法术",
    "Agonizing Rebuke": "法术",
    "Air Geyser": "法术",
    "Akashic Form": "法术",
    "Alter Musical Instrument": "法术",
    "Guiding Star": "法术",
    "Lightning Lash Bomb Admixture": "法术",
    "Snapdragon Fireworks": "法术",
    "Summoner Conduit": "法术",
    "Savage Maw": "法术",
    "Bleed For Your Master": "法术",

    # ===== 职业能力 / 职业特性 =====
    "Increased Damage Reduction": "职业能力",
    "Intimidating Glare": "职业能力",
    "Trap Spotter": "职业能力",
    "Psychic Sensitivity": "职业能力",
    "Stand Up": "职业能力",
    "Metal Blast": "职业能力",
    "Frightening Appearance": "职业能力",
    "Quick Change": "职业能力",
    "Vigilante Identity": "职业能力",
    "A Thousand Faces": "职业能力",
    "Wayfinder Revelation": "职业能力",
    "Animal Fury": "职业能力",
    "Channel Positive Energy": "职业能力",
    "Light Sensitivity": "状态/条件",
    "Positive Blast": "职业能力",
    "Horse Lord": "职业能力",
    "Deadly Dealer": "专长",
    "Lore Master": "职业能力",
    "Body Capacitance": "职业能力",
    "Persistent Vigor": "职业能力",
    "Guarded Stance": "职业能力",
    "Terrifying Howl": "职业能力",
    "Infusion Specialization": "职业能力",
    "Internal Buffer": "职业能力",
    "Pack Lord": "职业能力",
    "Kinetic Blade": "职业能力",
    "Healing Burst": "职业能力",
    "Nauseating Flesh": "职业能力",
    "Night Vision": "职业能力",
    "No Escape": "职业能力",
    "Obsidian Flow": "职业能力",
    "Primal Scent": "职业能力",
    "Serial Killer": "职业能力",
    "Shift Earth": "职业能力",
    "Swift Foot": "职业能力",
    "Timeless Body": "职业能力",
    "Vestigial Arm": "职业能力",
    "Verdant Blast": "职业能力",
    "Boasting Taunt": "职业能力",
    "Bottled Ooze": "职业能力",
    "Djinni Spin": "职业能力",
    "Doppelganger Simulacrum": "职业能力",
    "Earth Blast": "职业能力",
    "Efreeti Stance": "职业能力",
    "Efreeti Style": "职业能力",
    "Evil Eye": "职业能力",
    "Fire Blast": "职业能力",
    "Great Fortitude": "专长",
    "Green Tongue": "职业能力",
    "Heroic Defiance": "职业能力",
    "Heroic Recovery": "职业能力",
    "Janni Rush": "职业能力",
    "Janni Style": "职业能力",
    "Janni Tempest": "职业能力",
    "Ledge Walker": "职业能力",
    "Loyal Aid": "职业能力",
    "Many Guises": "职业能力",
    "Marid Coldsnap": "职业能力",
    "Marid Spirit": "职业能力",
    "Marid Style": "职业能力",
    "Telekinetic Blast": "职业能力",
    "Amateur Swashbuckler": "专长",
    "Haunt Channeler": "职业能力",
    "Spirit Guide": "职业能力",
    "Feral Speech": "职业能力",
    "Dueling Resolve": "职业能力",
    "Foe Throw": "职业能力",
    "Lucid Dreamer": "职业能力",
    "Aura Mastery": "职业能力",
    "Green Faith Acolyte": "职业能力",
    "Storm Kindler": "职业能力",
    "Tattooed Mystic": "职业能力",

    # ===== 专长 =====
    "Deific Obedience": "专长",
    "Deft Hands": "专长",
    "Second Chance": "专长",
    "Scale Spikes": "专长",
    "Ricochet Shot": "专长",
    "Strike Back": "专长",
    "Upkeep Phase": "规则概念",
    "Rolling Dodge": "职业能力",
    "Roused Anger": "职业能力",

    # ===== 装备/物品 =====
    "Alchemical Tools": "装备/物品",
    "Flaming Burst": "装备/物品",
    "Icy Burst": "装备/物品",
    "Shocking Burst": "装备/物品",
    "IOUN STONE": "装备/物品",
    "PEARL OF POWER": "装备/物品",
    "Cold Iron": "装备/物品",
    "Alchemical Remedies": "装备/物品",
    "Azure Briolette Ioun Stone": "装备/物品",
    "Exotic Saddle": "装备/物品",
    "Infernal Cord": "装备/物品",
    "HEADBAND OF VAST INTELLIGENCE": "装备/物品",
    "HEADBAND OF AERIAL AGILITY": "装备/物品",
    "Legal Pearlescent Pyramid Ioun Stone": "装备/物品",
    "PRESERVING FLASK": "装备/物品",
    "BORO BEAD": "装备/物品",
    "Stun Gun": "装备/物品",
    "Phase Locking": "装备/物品",
    "Corrosive Burst": "装备/物品",
    "BAG OF HOLDING": "装备/物品",
    "FEATHER TOKEN": "装备/物品",
    "Ioun Stone": "装备/物品",

    # ===== 神祇 / 宗教 =====
    "Sacred Colors": "神祇",
    "Holy Days": "神祇",
    "High Priest": "神祇",
    "Count Ranalc": "神祇",
    "Sacred Animal": "神祇",
    "Hei Feng": "神祇",
    "The Mother": "神祇",
    "The Lantern King": "神祇",
    "General Susumu": "神祇",
    "Town Hall": "组织/势力",

    # ===== 地域 / 位面 =====
    "Sodden Lands": "地域",
    "The Shackles": "地域",
    "Mana Wastes": "地域",
    "Distant Realms": "位面",

    # ===== 规则概念 =====
    "Honor Points": "规则概念",
    "Critical Failure": "规则概念",
    "Hit Dice": "规则概念",
    "Base Price": "规则概念",
    "Campaign Use": "规则概念",
    "Settlement Modifiers": "规则概念",
    "Build Points": "规则概念",
    "Core Rulebook": "来源书籍",
    "Animal Companion": "规则概念",

    # ===== 怪物/生物 =====
    "Deep One": "怪物/生物",
    "Dire Rat": "怪物/生物",
    "Shadow Mastiff": "怪物/生物",
}
