"""PF 1e 术语表 Phase 3 规则数据

本模块包含分类覆盖表、来源书识别、多信号分类规则和翻译清洗规则，
供 cleanup_phase3.py 与 verify_phase3.py 使用。
"""

# =============================================================================
# 来源书识别
# =============================================================================

SOURCE_BOOKS = {
    "Pathfinder RPG Core Rulebook",
    "Pathfinder RPG Bestiary",
    "Pathfinder RPG Bestiary 2",
    "Pathfinder RPG Bestiary 3",
    "Pathfinder RPG Bestiary 4",
    "Pathfinder RPG Bestiary 5",
    "Advanced Class Guide",
    "Advanced Player's Guide",
    "Advanced Race Guide",
    "Ultimate Magic",
    "Ultimate Combat",
    "Ultimate Intrigue",
    "Ultimate Wilderness",
    "Ultimate Equipment",
    "Mythic Adventures",
    "Occult Adventures",
    "Horror Adventures",
    "Technology Guide",
    "Inner Sea Gods",
    "Inner Sea Magic",
    "The Inner Sea World Guide",
    "Pathfinder Player Companion",
    "Pathfinder Society",
    "Adventurer's Guide",
    "Villain Codex",
    "Monster Codex",
    "Horror Adventures",
    "Martial Arts Handbook",
    "Armor Master's Handbook",
    "Weapon Master's Handbook",
    "Undead Slayer's Handbook",
    "Monster Summoner's Handbook",
    "Dirty Tactics Toolbox",
    "Magic Tactics Toolbox",
    "Melee Tactics Toolbox",
    "Ranged Tactics Toolbox",
    "Aquatic Adventures",
    "Planar Adventures",
    "Blood of Angels",
    "Blood of Fiends",
    "Blood of Shadows",
    "Blood of the Beast",
    "Blood of the Moon",
    "Blood of the Night",
    "Blood of the Elements",
    "Elemental Master's Handbook",
    "Wilderness Origins",
    "Arcane Anthology",
    "Healer's Handbook",
    "Alchemy Manual",
    "Antihero's Handbook",
    "Spymaster's Handbook",
    "Plane-Hopper's Handbook",
    "Monster Hunter's Handbook",
    "Demon Hunter's Handbook",
    "Dragonslayer's Handbook",
    "Haunted Heroes Handbook",
    "Heroes of the High Court",
    "Heroes of the Darklands",
    "Heroes of the Streets",
    "Heroes of Golarion",
    "Halflings of Golarion",
    "Dwarves of Golarion",
    "Elves of Golarion",
    "Gnomes of Golarion",
    "Orcs of Golarion",
    "Goblins of Golarion",
    "Kobolds of Golarion",
    "Taldor",
    "Irrisen",
    "Cheliax",
    "Andoran",
    "Qadira",
    "Osirion",
    "Kyonin",
    "Varisia",
    "Absalom",
    "Korvosa",
    "Magnimar",
    "Riddleport",
    "Kaer Maga",
    "Sandpoint",
    "Crown of the World",
    "Storval Plateau",
    "Inner Sea",
    "Golarion",
}

SOURCE_BOOK_TRANSLATIONS = {
    "Pathfinder RPG Core Rulebook": "核心规则手册",
    "Pathfinder RPG Bestiary": "怪物图鉴",
    "Pathfinder RPG Bestiary 2": "怪物图鉴2",
    "Pathfinder RPG Bestiary 3": "怪物图鉴3",
    "Pathfinder RPG Bestiary 4": "怪物图鉴4",
    "Pathfinder RPG Bestiary 5": "怪物图鉴5",
    "Advanced Class Guide": "进阶职业手册",
    "Advanced Player's Guide": "进阶玩家手册",
    "Advanced Race Guide": "进阶种族手册",
    "Ultimate Magic": "极限魔法",
    "Ultimate Combat": "极限战斗",
    "Ultimate Intrigue": "极限诡道",
    "Ultimate Wilderness": "极限荒野",
    "Ultimate Equipment": "极限装备",
    "Mythic Adventures": "神话冒险",
    "Occult Adventures": "异能冒险",
    "Horror Adventures": "惧怖冒险",
    "Technology Guide": "科技指南",
    "Inner Sea Gods": "内海诸神",
    "Inner Sea Magic": "内海魔法",
    "The Inner Sea World Guide": "内海世界指南",
    "Pathfinder Player Companion": "玩家伴侣",
    "Pathfinder Society": "探索者协会",
    "Adventurer's Guide": "冒险者指南",
    "Villain Codex": "反派法典",
    "Monster Codex": "怪物法典",
    "Martial Arts Handbook": "武术手册",
    "Armor Master's Handbook": "护甲大师手册",
    "Weapon Master's Handbook": "武器大师手册",
    "Undead Slayer's Handbook": "亡灵杀手手册",
    "Monster Summoner's Handbook": "怪物召唤者手册",
    "Dirty Tactics Toolbox": "阴招战术工具箱",
    "Magic Tactics Toolbox": "魔法战术工具箱",
    "Melee Tactics Toolbox": "近战战术工具箱",
    "Ranged Tactics Toolbox": "远程战术工具箱",
    "Aquatic Adventures": "水下冒险",
    "Planar Adventures": "位面冒险",
    "Blood of Angels": "天界血脉",
    "Blood of Fiends": "炼狱血脉",
    "Blood of Shadows": "阴影血脉",
    "Blood of the Beast": "野兽血脉",
    "Blood of the Moon": "月之血脉",
    "Blood of the Night": "夜之血脉",
    "Blood of the Elements": "元素血脉",
    "Elemental Master's Handbook": "元素大师手册",
    "Wilderness Origins": "荒野起源",
    "Arcane Anthology": "奥术选集",
    "Healer's Handbook": "治疗者手册",
    "Alchemy Manual": "炼金术手册",
    "Antihero's Handbook": "反英雄手册",
    "Spymaster's Handbook": "间谍大师手册",
    "Plane-Hopper's Handbook": "位面行者手册",
    "Monster Hunter's Handbook": "怪物猎人手册",
    "Demon Hunter's Handbook": "恶魔猎人手册",
    "Dragonslayer's Handbook": "屠龙者手册",
    "Haunted Heroes Handbook": "闹鬼英雄手册",
    "Heroes of the High Court": "高庭英雄",
    "Heroes of the Darklands": "黑暗之地英雄",
    "Heroes of the Streets": "街头英雄",
    "Heroes of Golarion": "格拉里昂英雄",
    "Halflings of Golarion": "格拉里昂的半身人",
    "Dwarves of Golarion": "格拉里昂的矮人",
    "Elves of Golarion": "格拉里昂的精灵",
    "Gnomes of Golarion": "格拉里昂的侏儒",
    "Orcs of Golarion": "格拉里昂的兽人",
    "Goblins of Golarion": "格拉里昂的地精",
    "Kobolds of Golarion": "格拉里昂的狗头人",
    "Taldor": "塔尔多",
    "Irrisen": "艾利森",
    "Cheliax": "切利亚斯",
    "Andoran": "安多安",
    "Qadira": "卡迪拉",
    "Osirion": "奥斯里昂",
    "Kyonin": "基欧宁",
    "Varisia": "瓦瑞西亚",
    "Absalom": "艾巴萨罗姆",
    "Korvosa": "寇沃萨",
    "Magnimar": "玛格尼玛",
    "Riddleport": "谜港城",
    "Kaer Maga": "卡尔·玛迦",
    "Sandpoint": "沙点镇",
    "Crown of the World": "世界之冠",
    "Storval Plateau": "斯托瓦尔高原",
    "Inner Sea": "内海",
    "Golarion": "格拉里昂",
}

# =============================================================================
# 精确分类覆盖表
# =============================================================================

CATEGORY_OVERRIDES = {
    # 边界案例
    "Fast Movement": "职业能力",
    "Quick Draw": "专长",
    "Countless Eyes": "法术",
    "Energy Siege Shot": "法术",
    "Storval Plateau": "地域",

    # 高优先级误分类：法术
    "Neutralize Poison": "法术",
    "Remove Disease": "法术",
    "Detect Poison": "法术",
    "Detect Undead": "法术",
    "Plant Growth": "法术",
    "Cure Moderate Wounds": "法术",
    "Cure Light Wounds": "法术",
    "Repel Vermin": "法术",
    "Faerie Fire": "法术",
    "Gaseous Form": "法术",
    "Raise Dead": "法术",
    "Modify Memory": "法术",
    "Endure Elements": "法术",
    "Phantom Steed": "法术",
    "Unseen Servant": "法术",
    "Mind Blank": "法术",
    "Flame Blade": "法术",
    "Earth Glide": "法术",
    "Animate Dead": "法术",
    "Water Walk": "法术",
    "True Strike": "法术",
    "Ice Storm": "法术",
    "Phantasmal Killer": "法术",
    "Dominate Animal": "法术",
    "Time Stop": "法术",
    "Water Breathing": "法术",
    "Temporal Stasis": "法术",
    "Good Hope": "法术",
    "False Life": "法术",
    "Telepathic Bond": "法术",
    "Scorching Ray": "法术",
    "Legend Lore": "法术",
    "Comprehend Languages": "法术",
    "Gentle Repose": "法术",
    "Command Plants": "法术",
    "Detect Magic": "法术",
    "Magic Missile": "法术",
    "Lightning Bolt": "法术",
    "Summon Monster IV": "法术",
    "Unholy Blight": "法术",
    "Holy Smite": "法术",
    "Fire Storm": "法术",
    "Dominate Monster": "法术",
    "Crushing Despair": "法术",
    "Hydraulic Push": "法术",
    "Vocal Alteration": "法术",
    "Ghostbane Dirge": "法术",
    "Sepia Snake Sigil": "法术",
    "Antiplant Shell": "法术",
    "Unbreakable Construct": "法术",
    "Ghost Touch": "法术",
    "Disrupt Undead": "法术",
    "Repair Undead": "法术",
    "Elemental Touch": "法术",
    "Battlemind Link": "法术",
    "Raise Animal Companion": "法术",

    # 高优先级误分类：专长
    "Combat Expertise": "专长",
    "Weapon Focus": "专长",
    "Weapon Specialization": "专长",
    "Improved Trip": "专长",
    "Improved Disarm": "专长",
    "Improved Bull Rush": "专长",
    "Improved Grapple": "专长",
    "Improved Feint": "专长",
    "Improved Initiative": "专长",
    "Improved Sunder": "专长",
    "Improved Reposition": "专长",
    "Power Attack": "专长",
    "Cleave": "专长",
    "Dodge": "专长",
    "Mobility": "专长",
    "Spring Attack": "专长",
    "Whirlwind Attack": "专长",
    "Skill Focus": "专长",
    "Spell Penetration": "专长",
    "Greater Spell Penetration": "专长",
    "Toughness": "专长",
    "Alertness": "专长",
    "Acrobatic": "专长",
    "Stealthy": "专长",
    "Self-Sufficient": "专长",
    "Persuasive": "专长",
    "Deceitful": "专长",
    "Negotiator": "专长",
    "Magical Aptitude": "专长",
    "Athletic": "专长",
    "Endurance": "专长",
    "Acrobatic Steps": "专长",
    "Mounted Combat": "专长",
    "Nimble Moves": "专长",
    "Improved Critical": "专长",
    "Critical Focus": "专长",
    "Step Up": "专长",
    "Agile Maneuvers": "专长",
    "Stunning Fist": "专长",
    "Blind-Fight": "专长",
    "Combat Casting": "专长",
    "Dazzling Display": "专长",
    "Deadly Aim": "专长",
    "Pinpoint Targeting": "专长",
    "Wind Stance": "专长",
    "Intimidating Prowess": "专长",
    "Eschew Materials": "专长",
    "Dampen Presence": "专长",
    "Greater Sunder": "专长",
    "Bleeding Critical": "专长",
    "Disarming Strike": "专长",

    # 职业能力 / 职业特性
    "Combat Trick": "职业能力",
    "Elemental Overflow": "职业能力",
    "Elemental Whisper": "职业能力",
    "Elemental Grip": "职业能力",
    "Elemental Focus": "职业能力",
    "Wild Talents": "职业能力",
    "Wild Talent": "职业能力",
    "Rogue Talents": "职业能力",
    "Rogue Talent": "职业能力",
    "Social Talent": "职业能力",
    "Ki Pool": "职业能力",
    "Ki Shout": "职业能力",
    "Favored Enemy": "职业能力",
    "Favored Terrain": "职业能力",
    "Sneak Attack": "职业能力",
    "Rage Powers": "职业能力",
    "Bloodline Powers": "职业能力",
    "Bardic Performance": "职业能力",
    "Inspire Courage": "职业能力",
    "Inspire Competence": "职业能力",
    "Bravery": "职业能力",
    "Armor Training": "职业能力",
    "Studied Target": "职业能力",
    "Phrenic Amplification": "职业能力",
    "Mental Focus": "职业能力",
    "Painful Stare": "职业能力",
    "Hypnotic Stare": "职业能力",
    "Bold Stare": "职业能力",
    "Wild Empathy": "职业能力",
    "Wild Shape": "法术",
    "Beast Totem": "职业能力",
    "Fiend Totem": "职业能力",
    "Mounted Combat": "专长",
    "Beast Totem, Lesser": "职业能力",
    "Beast Totem, Greater": "职业能力",
    "Construction Points": "怪物/生物",
    "Clockwork Familiar": "怪物/生物",

    # 技能
    "Sense Motive": "技能",
    "Handle Animal": "技能",
    "Disable Device": "技能",
    "Escape Artist": "技能",
    "Acrobatics": "技能",
    "Perception": "技能",
    "Stealth": "技能",
    "Spellcraft": "技能",
    "Knowledge": "技能",
    "Survival": "技能",
    "Diplomacy": "技能",
    "Bluff": "技能",
    "Climb": "技能",
    "Swim": "技能",
    "Ride": "技能",
    "Use Magic Device": "技能",
    "Fly": "技能",
    "Heal": "技能",
    "Intimidate": "技能",
    "Perform": "技能",
    "Profession": "技能",
    "Linguistics": "技能",
    "Appraise": "技能",
    "Disguise": "技能",
    "Sleight of Hand": "技能",
    "Concentration": "技能",

    # 状态/条件
    "Crushing Despair": "法术",
    "Shaken": "状态/条件",
    "Sickened": "状态/条件",
    "Demon Fever": "状态/条件",
    "Filth Fever": "状态/条件",
    "Red Ache": "状态/条件",
    "Blinded": "状态/条件",
    "Confused": "状态/条件",
    "Dazed": "状态/条件",
    "Dazzled": "状态/条件",
    "Deafened": "状态/条件",
    "Entangled": "状态/条件",
    "Exhausted": "状态/条件",
    "Fatigued": "状态/条件",
    "Frightened": "状态/条件",
    "Grappled": "状态/条件",
    "Helpless": "状态/条件",
    "Invisible": "状态/条件",
    "Nauseated": "状态/条件",
    "Panicked": "状态/条件",
    "Paralyzed": "状态/条件",
    "Petrified": "状态/条件",
    "Pinned": "状态/条件",
    "Prone": "状态/条件",
    "Staggered": "状态/条件",
    "Stunned": "状态/条件",
    "Unconscious": "状态/条件",
    "Flat-Footed": "状态/条件",
    "Bleed": "状态/条件",

    # 装备/物品
    "MASK OF GIANTS": "装备/物品",
    "VAMBRACES OF THE GENIE": "装备/物品",
    "CROWN OF BLASTING": "装备/物品",
    "SNIPER GOGGLES": "装备/物品",
    "Ghost Touch": "装备/物品",

    # 规则概念 / 动作
    "Charge Object": "规则概念",
    "Tree Stride": "法术",
    "Object Reading": "职业能力",
    "Third Eye": "职业能力",
    "Fiendish Obedience": "专长",
}

# =============================================================================
# 多信号分类规则（用于无精确覆盖时）
# =============================================================================

# 法术信号：译名后缀 / 关键词
SPELL_SIGNALS = {
    "suffixes": [
        "术", "法球", "护盾", "结界", "祝福", "诅咒", "光辉", "黑暗",
        "幻象", "传送", "召唤", "控制", "治疗", "伤害", "防护", "侦测",
        "解除", "变形", "隐形", "加速", "减速", "定身", "魅惑", "恐惧",
        "燃烧", "冰冻", "闪电", "酸液", "音波", "锁链", "之触", "之手",
        "护甲", "武器", "步伐", "行走", "形态", "光环", "领域", "风暴",
        "射线", "飞弹", "箭矢", "盔甲", "护罩", "打击", "冲击", "轰鸣",
    ],
    "keywords": ["法术", "咒语", "施法", "环级", "豁免", "法器", "材料成分", "学派"],
    "english_suffixes": ["spell", "magic", "arcane", "divine"],
}

# 专长信号
FEAT_SIGNALS = {
    "prefixes": [
        "Improved ", "Greater ", "Superior ", "Weapon Focus", "Weapon Specialization",
        "Combat ", "Blind-Fight", "Dodge", "Mobility", "Spring Attack",
        "Whirlwind", "Cleave", "Power Attack", "Skill Focus", "Spell Penetration",
        "Toughness", "Alertness", "Acrobatic", "Stealthy", "Athletic",
        "Endurance", "Persuasive", "Deceitful", "Negotiator", "Self-Sufficient",
        "Magical Aptitude", "Deadly Aim", "Pinpoint Targeting", "Step Up",
        "Agile Maneuvers", "Stunning Fist", "Wind Stance", "Critical Focus",
        "Intimidating Prowess", "Dazzling Display", "Dampen Presence",
    ],
    "keywords": ["专长", "先决条件", "战斗专长"],
    "english_suffixes": ["feat"],
}

# 职业能力信号
CLASS_FEATURE_SIGNALS = {
    "suffixes": [
        "Talents", "Powers", "Pool", "Training", "Performance", "Bond",
        "Sense", "Link", "Rage", "Smite", "Ki ", "Favored", "Stare",
        "Amplification", "Focus", "Empathy", "Shape", "Totem", "Talent",
    ],
    "keywords": ["职业能力", "职业特性", "每日", "轮数", "先知等级"],
}

# 技能精确列表
SKILL_SIGNALS = {
    "exact": [
        "Acrobatics", "Appraise", "Bluff", "Climb", "Craft", "Diplomacy",
        "Disable Device", "Disguise", "Escape Artist", "Fly", "Handle Animal",
        "Heal", "Intimidate", "Knowledge", "Linguistics", "Perception",
        "Perform", "Profession", "Ride", "Sense Motive", "Sleight of Hand",
        "Spellcraft", "Stealth", "Survival", "Swim", "Use Magic Device",
        "Concentration",
    ],
}

# 状态/条件精确列表
CONDITION_SIGNALS = {
    "exact": [
        "Blinded", "Confused", "Dazed", "Dazzled", "Deafened", "Entangled",
        "Exhausted", "Fatigued", "Frightened", "Grappled", "Helpless",
        "Invisible", "Nauseated", "Panicked", "Paralyzed", "Petrified",
        "Pinned", "Prone", "Shaken", "Sickened", "Staggered", "Stunned",
        "Unconscious", "Flat-Footed", "Bleed",
    ],
}

# 装备/物品信号
EQUIPMENT_SIGNALS = {
    "keywords": [
        "武器", "防具", "护甲", "盾牌", "药水", "卷轴", "魔杖", "法杖",
        "戒指", "项链", "斗篷", "靴子", "手套", "头盔", "腰带", "护腕",
        "钉头锤", "长剑", "弯刀", "战斧", "长弓", "短剑", "匕首", "长矛",
        "链甲", "皮甲", "板甲", "鳞甲", "奇物", "附魔",
    ],
    "english_keywords": [
        "sword", "armor", "shield", "potion", "scroll", "wand", "staff",
        "ring", "amulet", "cloak", "boots", "belt", "bracers", "gauntlet",
        "helm", "dagger", "mace", "spear", "bow", "arrow", "crossbow",
        "item", "weapon", "rod", "wondrous", "figurine",
    ],
}

# 怪物/生物信号（用于保留而非吸引法术）
CREATURE_SIGNALS = {
    "exact": [
        "Goblin", "Orc", "Elf", "Dwarf", "Halfling", "Gnome", "Human",
        "Half-Elf", "Half-Orc", "Tiefling", "Aasimar", "Skeleton", "Zombie",
        "Ghost", "Vampire", "Lich", "Demon", "Devil", "Angel", "Celestial",
        "Fiend", "Fey", "Giant", "Troll", "Ogre", "Wolf", "Bear", "Lion",
        "Snake", "Spider", "Rat", "Bat", "Raven", "Eagle", "Hawk", "Vermin",
        "Ooze", "Outsider", "Aberration", "Magical Beast", "Dragon",
    ],
    "keywords": ["怪物", "生物", "种族", "亚种"],
}

# =============================================================================
# 翻译清洗规则
# =============================================================================

# 描述性前缀，迭代剥离
DESCRIPTION_PREFIXES = [
    "该能力改变了", "该能力取代", "该能力取代了", "该能力调整了", "该能力在其他方面都",
    "该法术的功能如同", "这个法术工作方式如同", "此能力如同",
    "该效果在其他方面的功能都", "该效果在判断包含", "此奖励",
    "该武器价格与重量和同书的", "这个物品基本等同于",
    "使得圣物猎手可以使用存有这些法术的", "若佩戴者能够施放",
    "每当魔宠的主人施放", "任何被", "天赋与", "和次等",
    "级获得", "级起使用", "你必须选择", "可以施展", "必须信奉",
    "职业能力", "智力调整值", "对所选近战武器拥有战士",
    "对所选远程武器拥有战士", "且你对它拥有战士的", "战士",
    "你能够", "由该法术造出的水在其他方面与", "生效的",
    "就好像受到了", "或解除", "个骰子来获得", "分钟的法术",
    "施放一次法术", "他们能够以类法术能力施放",
    "所有你的听众都会受到一个法术", "一个受到法术",
    "等级该法术的功能如同", "你无法通过共鸣通道来使用",
    "此类持续时间的延长不会与", "法术就如同被狂怒变形者使用",
    "就如同使用", "你可以用", "此武器同样获得", "匕首可以像",
    "你可以对目标施加法术", "之类的法术仍旧会如常侦测到",
    "身体", "神话", "版本的", "专长或者",
    "若一个身体成为了", "她将", "类似", "次",
    "那么他会立即受到", "并且这个法术可以被",
    "他们可以以类法术能力施放", "你可以施放", "你可以如同",
    "穿戴者被视为受到常驻的", "这个动物会获得",
    "这类似于", "这被视为", "这如同", "就如同", "类似",
    "和", "或", "不过", "即使", "一旦", "由于", "那么",
    "此能力调整了", "此能力替代", "这取代了", "这改变了",
    "能力并替代了", "不过它还能够额外提供",
    "该能力在其他方面都", "该能力取代了", "该能力改变了",
    "此能力替代", "这取代了", "这改变了", "能力并替代了",
    "就如同", "类似", "和", "或", "次",
    "这些凶蛮的武器由", "这种问题对于生活在", "这种",
    "如果你还具有", "或", "并且", "以及",
]

# 不良开头：推荐翻译不能以这些字/词开头
# 只保留明显是上下文/描述性的开头；单字容易误伤合法译名，尽量用多字短语
BAD_STARTS = [
    "该", "这个", "这些", "那些", "此", "这", "每当", "任何", "如果",
    "你", "他", "她", "它", "你的", "他的", "她的", "它的",
    "可以", "能够", "会", "将", "使", "让", "被", "受到", "遭受", "获得",
    " minutes", " hours", " rounds", " level", " levels",
]

# 句法粒子：用于判断是否为句子/片段
SENTENCE_PARTICLES = [
    "的", "了", "在", "被", "让", "使", "可以", "能够", "会", "将", "如果",
    "每当", "并且", "以及", "因此", "所以", "但是", "不过", "就像", "如同",
    "受到", "获得", "取代", "调整", "改变", "使用", "施放", "具有", "拥有",
    "选择", "通过", "以此", "比如", "例如", "之类", "等", "中", "内", "上",
    "下", "里", "外", "时", "后", "前", "之间", "之间", "对于", "关于",
    "由于", "因为", "所以", "虽然", "但是", "然而", "如果", "即使", "除非",
    "尽管", "不仅", "而且", "既", "又", "也", "还", "才", "就", "都",
    "只", "仅", "正好", "刚好", "已经", "曾经", "正在", "将要", "就要",
]

# 分类输出顺序（新增 来源书籍）
CATEGORY_ORDER = [
    "法术", "专长", "职业能力", "状态/条件", "装备/物品", "技能",
    "怪物/生物", "动作/战技", "位面", "神祇", "种族", "地域",
    "组织/势力", "规则概念", "来源书籍", "其他",
]

# 翻译长度限制
MAX_RECOMMENDED_LEN = 15
MAX_OTHER_LEN = 12
MIN_TRANSLATION_LEN = 2
